import { NextResponse } from "next/server";

const data = {
  email: "email@email.com",
  firstName: "Purely",
  lastName: "Fictitious",
}

export async function GET() {
  await new Promise(res => setTimeout(res, 2000));
  return NextResponse.json({ 
    success: false, 
    message: "Could not get profile -- message generated by api route", 
  }, { status: 500 });
}
export async function PUT(req: Request) {
  await new Promise(res => setTimeout(res, 2000));
  return NextResponse.json({ 
    success: false, 
    message: "Could not save -- message generated by api route" 
  }, { status: 500 });
}